services:
  - type: web
    name: hotelreserve
    env: docker
    plan: free
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_ROOT
        value: ""
