CREATE DATABASE IF NOT EXISTS bookreserve_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bookreserve_db;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS notifications,activity_logs,reservations,book_copies,books,publishers,authors,categories,users;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,first_name VARCHAR(80) NOT NULL,last_name VARCHAR(80) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,student_id VARCHAR(60) NOT NULL UNIQUE,phone VARCHAR(50),address TEXT,role ENUM('user','admin') NOT NULL DEFAULT 'user',status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(role,status));
CREATE TABLE categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,description TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE authors(id INT AUTO_INCREMENT PRIMARY KEY,first_name VARCHAR(80) NOT NULL,last_name VARCHAR(80) NOT NULL,biography TEXT,birth_date DATE NULL,image VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE publishers(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL UNIQUE,address TEXT,email VARCHAR(160),phone VARCHAR(50),website VARCHAR(200),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE books(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,isbn VARCHAR(30) NOT NULL UNIQUE,description TEXT,publication_year SMALLINT,pages SMALLINT,language VARCHAR(50) DEFAULT 'English',cover_image VARCHAR(255),author_id INT NOT NULL,publisher_id INT NOT NULL,category_id INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(title),INDEX(author_id),INDEX(publisher_id),INDEX(category_id),FOREIGN KEY(author_id) REFERENCES authors(id) ON DELETE RESTRICT,FOREIGN KEY(publisher_id) REFERENCES publishers(id) ON DELETE RESTRICT,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE RESTRICT);
CREATE TABLE book_copies(id INT AUTO_INCREMENT PRIMARY KEY,book_id INT NOT NULL,accession_number VARCHAR(80) NOT NULL UNIQUE,status ENUM('AVAILABLE','RESERVED','BORROWED','LOST','DAMAGED','MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE',location VARCHAR(120),`condition` VARCHAR(80) DEFAULT 'Good',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(book_id),INDEX(status),FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE RESTRICT);
CREATE TABLE reservations(id INT AUTO_INCREMENT PRIMARY KEY,reservation_number VARCHAR(30) NOT NULL UNIQUE,user_id INT NOT NULL,book_id INT NOT NULL,copy_id INT NOT NULL,status ENUM('PENDING','APPROVED','READY_FOR_PICKUP','BORROWED','RETURNED','COMPLETED','CANCELLED','REJECTED','EXPIRED') NOT NULL DEFAULT 'PENDING',reserved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,approved_at DATETIME NULL,pickup_deadline DATETIME NULL,borrowed_at DATETIME NULL,due_date DATETIME NULL,returned_at DATETIME NULL,cancelled_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(user_id),INDEX(book_id),INDEX(copy_id),INDEX(status),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE RESTRICT,FOREIGN KEY(copy_id) REFERENCES book_copies(id) ON DELETE RESTRICT);
CREATE TABLE activity_logs(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,action VARCHAR(100) NOT NULL,entity_type VARCHAR(80),entity_id INT NULL,description TEXT,ip_address VARCHAR(45),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(created_at),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE notifications(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,title VARCHAR(180) NOT NULL,message TEXT NOT NULL,type ENUM('RESERVATION','APPROVAL','READY','BORROWED','RETURNED','OVERDUE','SYSTEM') NOT NULL DEFAULT 'SYSTEM',is_read TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id,is_read),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

INSERT INTO users(first_name,last_name,email,password,student_id,role) VALUES
('Admin','Librarian','admin@bookreserve.local','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','ADMIN-001','admin'),('Maria','Santos','maria.admin@bookreserve.local','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','ADMIN-002','admin'),
('Ava','Reyes','ava@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-001','user'),('Ben','Cruz','ben@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-002','user'),('Cara','Lim','cara@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-003','user'),('Dion','Tan','dion@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-004','user'),('Elle','Go','elle@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-005','user'),('Finn','Yu','finn@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-006','user'),('Gia','Lee','gia@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-007','user'),('Hugo','Dela Cruz','hugo@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-008','user'),('Ivy','Chua','ivy@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-009','user'),('Jules','Ong','jules@example.test','$2y$10$UoHyfw/uUilYooIJpE4NK..weYiUd3BGiRJhHGnopdHQ5mC8vj/bW','STU-010','user');
INSERT INTO categories(name,description) VALUES ('Fiction','Stories and novels'),('Science','Scientific study'),('Technology','Modern technology'),('Programming','Software development'),('History','Past events'),('Mathematics','Mathematical study'),('Literature','Classic writing'),('Business','Leadership and enterprise');
INSERT INTO authors(first_name,last_name,biography) VALUES ('Mira','Vale','Fiction writer'),('Noah','Stone','Science educator'),('Lena','Park','Technology author'),('Owen','Reid','Programming author'),('Sofia','Hart','Historian'),('Theo','Wells','Mathematics writer'),('Nina','Bloom','Literature professor'),('Evan','Ford','Business analyst'),('Rina','Cole','Researcher'),('Marco','Vega','Educator');
INSERT INTO publishers(name,email) VALUES ('North Star Press','hello@northstar.test'),('Campus House','info@campushouse.test'),('Blue Shelf','contact@blueshelf.test'),('Atlas Books','info@atlas.test'),('Bright Leaf','hello@brightleaf.test');
DELIMITER $$
CREATE PROCEDURE seed_books() BEGIN DECLARE i INT DEFAULT 1; WHILE i<=30 DO INSERT INTO books(title,isbn,description,publication_year,pages,language,author_id,publisher_id,category_id) VALUES(CONCAT('Library Collection Volume ',i),CONCAT('978000000',LPAD(i,4,'0')),CONCAT('A fictional sample library book, volume ',i,'.'),2010+i,180+i,'English',1+MOD(i-1,10),1+MOD(i-1,5),1+MOD(i-1,8)); SET i=i+1; END WHILE; END$$
CALL seed_books()$$ DROP PROCEDURE seed_books$$
CREATE PROCEDURE seed_copies() BEGIN DECLARE i INT DEFAULT 1; DECLARE n INT DEFAULT 1; WHILE i<=30 DO SET n=1; WHILE n<=2 DO INSERT INTO book_copies(book_id,accession_number,status,location,`condition`) VALUES(i,CONCAT('BR-',LPAD(i,3,'0'),'-',LPAD(n,2,'0')),'AVAILABLE',CONCAT('Shelf ',1+MOD(i,9)),'Good'); SET n=n+1; END WHILE; SET i=i+1; END WHILE; END$$
CALL seed_copies()$$ DROP PROCEDURE seed_copies$$
DELIMITER ;
-- Development credentials: admin@bookreserve.local / Admin@12345. Change before production.
